# Configuration Manalytics - Phase 2 Production
app_name: Manalytics
version: 2.0.0
environment: production

# Scraping
scraping:
  cache_folder: "./data"
  max_retries: 5
  rate_limit: 0.5
  timeout: 30

# API REST uniquement (pas de GraphQL)
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  cors_origins: ["*"]
  rate_limit: "100/minute"

# Cache Redis
redis:
  host: "localhost"
  port: 6379
  db: 0
  ttl_default: 3600

# Monitoring
monitoring:
  prometheus_port: 9090
  log_level: "INFO"
  sentry_dsn: ""  # À configurer

# Pas de ML, Dashboard, WebSocket, etc.
features:
  enable_ml: false
  enable_dashboard: false
  enable_realtime: false
  enable_predictions: false
