cache_folder: "./data"
format_data_path: "./MTGOFormatData"
enabled_sources: ["melee", "mtgo", "topdeck"]

apis:
  melee:
    login_file: "./credentials/melee_login.json"
  topdeck:
    api_key_file: "./credentials/topdeck_api.txt"
  mtgo:
    # Pas d'auth requise pour MTGO

scraping:
  max_retries: 5
  retry_delay: 2
  concurrent_requests: 10
  rate_limit_delay: 0.5
  timeout: 30

classification:
  min_confidence: 0.8
  unknown_threshold: 5  # % max d'unknown accepté
  fallback_enabled: true

analysis:
  min_matches_for_matchup: 10
  confidence_interval: 0.95
  min_decks_for_archetype: 5

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_log_files: 10 