name: onboarding-guard
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - id: diff
        run: |
          DOCS=$(git diff --name-only origin/main...HEAD | grep -E '^docs/|^README.md' || true)
          CODE=$(git diff --name-only origin/main...HEAD | grep -E '^src/|^config/|^scripts/' || true)
          echo "docs=$DOCS" >> $GITHUB_OUTPUT
          echo "code=$CODE" >> $GITHUB_OUTPUT

      - name: Fail if code changes but docs untouched
        if: steps.diff.outputs.code != '' && steps.diff.outputs.docs == ''
        run: |
          echo "::error::Code modifié sans update du kit d'on-boarding." && exit 1 